FROM python:3.13.5-slim

WORKDIR /opt/prefect/prod/code

# Copy the local requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the context files INTO the specific outlook_automation subfolder
COPY . ./outlook_automation/

# Tell Python where the source code lives
ENV PYTHONPATH=/opt/prefect/prod/code/outlook_automation/src

# Command to run your flow
CMD ["python", "-m", "outlook_app.flows.email_extraction_flow"]
